language: cpp
sudo: false

matrix:
  include:

    - compiler: gcc
      sudo: true
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: COMPILER=g++-5 COVERAGE=1
    
    - compiler: gcc
      addons: &gcc5
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: COMPILER=g++-5 DEBUG=0
    
    - compiler: gcc
      addons: &gcc6
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: COMPILER=g++-6 DEBUG=0
    
    - compiler: clang
      addons: &clang36
        apt:
          sources: ['llvm-toolchain-precise-3.6', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.6']
      env: COMPILER=clang++-3.6 DEBUG=0
    
    - compiler: clang
      addons: &clang37
        apt:
          sources: ['llvm-toolchain-precise-3.7', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.7']
      env: COMPILER=clang++-3.7 DEBUG=0
    
    - compiler: clang
      addons: &clang38
        apt:
          sources: ['llvm-toolchain-precise-3.8', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.8']
      env: COMPILER=clang++-3.8 DEBUG=0

    - compiler: clang
      addons: &clang39
        apt:
          sources: ['llvm-toolchain-precise-3.9', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.9']
      env: COMPILER=clang++-3.9 DEBUG=0

    - compiler: gcc
      addons: *gcc5
      env: COMPILER=g++-5 DEBUG=1
    
    - compiler: gcc
      addons: *gcc6
      env: COMPILER=g++-6 DEBUG=1
    
    - compiler: clang
      addons: *clang36
      env: COMPILER=clang++-3.6 DEBUG=1
    
    - compiler: clang
      addons: *clang37
      env: COMPILER=clang++-3.7 DEBUG=1
    
    - compiler: clang
      addons: *clang38
      env: COMPILER=clang++-3.8 DEBUG=1

    - compiler: clang
      addons: *clang39
      env: COMPILER=clang++-3.9 DEBUG=1

branches:
    only:
        - /.*/
      
before_install:
    - if [ ${COVERAGE} == 1 ]; then
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50;
      sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 50;
      cd "${TRAVIS_BUILD_DIR}";
      wget "http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz";
      tar xf lcov_1.13.orig.tar.gz;
      cd "lcov-1.13/";
      sudo make install;
      fi

install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
    - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - https://cmake.org/files/v3.8/cmake-3.8.0-rc4-Linux-x86_64.tar.gz | tar --strip-components=1 -xz -C cmake
    - export PATH=${DEPS_DIR}/cmake/bin:${PATH}

before_script:
    - export CXX=${COMPILER}
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build && cd build
    - if [ ${COVERAGE} == 1 ];
      then cmake -DBUILD_EXAMPLES=0 -DCOVERAGE=1 ..;
      else cmake -DBUILD_TESTS=1 -DDEBUG=${DEBUG} ..;
      fi
      
script:
    - make -j 2

after_success:
    - ./tests -s -d yes
    - if [ ${COVERAGE} != 1 ]; then
      ./hello_world;
      ./square_root;
      ./salesman;
      ./ps_functions;
      ./sa_functions;
      else
      lcov --directory . --capture --output-file coverage.info;
      lcov --remove coverage.info '/usr/*' '*catch.hpp' --output-file coverage.info;
      lcov --list coverage.info;
      bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports";
      fi
